import type { YaoValue } from '@/types/zhouyi'

export const TRIGRAMS = [
  { name: 'qian', chineseName: '乾', element: '金', symbol: '☰', lines: [7, 7, 7] as YaoValue[] },
  { name: 'dui',  chineseName: '兑', element: '金', symbol: '☱', lines: [7, 7, 8] as YaoValue[] },
  { name: 'li',   chineseName: '离', element: '火', symbol: '☲', lines: [7, 8, 7] as YaoValue[] },
  { name: 'zhen', chineseName: '震', element: '木', symbol: '☳', lines: [7, 8, 8] as YaoValue[] },
  { name: 'xun',  chineseName: '巽', element: '木', symbol: '☴', lines: [8, 7, 7] as YaoValue[] },
  { name: 'kan',  chineseName: '坎', element: '水', symbol: '☵', lines: [8, 7, 8] as YaoValue[] },
  { name: 'gen',  chineseName: '艮', element: '土', symbol: '☶', lines: [8, 8, 7] as YaoValue[] },
  { name: 'kun',  chineseName: '坤', element: '土', symbol: '☷', lines: [8, 8, 8] as YaoValue[] },
]

export interface HexagramData {
  id: number; name: string; upper: number; lower: number
  judgment: string; image: string; lines: string[]
}

export const HEXAGRAMS: HexagramData[] = [
  { id: 1, name: '乾为天', upper: 0, lower: 0, judgment: '元亨利贞。', image: '天行健，君子以自强不息。', lines: ['潜龙勿用。','见龙在田。','终日乾乾。','或跃在渊。','飞龙在天。','亢龙有悔。'] },
  { id: 2, name: '坤为地', upper: 7, lower: 7, judgment: '元亨，利牝马之贞。', image: '地势坤，君子以厚德载物。', lines: ['履霜坚冰至。','直方大。','含章可贞。','括囊无咎。','黄裳元吉。','龙战于野。'] },
  { id: 3, name: '水雷屯', upper: 5, lower: 3, judgment: '元亨利贞，利建侯。', image: '云雷屯，君子以经纶。', lines: ['磐桓。','屯如邅如。','即鹿无虞。','求婚媾。','屯其膏。','泣血涟如。'] },
  { id: 4, name: '山水蒙', upper: 6, lower: 5, judgment: '亨，匪我求童蒙。', image: '山下出泉，君子以果行育德。', lines: ['发蒙。','包蒙吉。','勿用取女。','困蒙吝。','童蒙吉。','击蒙。'] },
  { id: 5, name: '水天需', upper: 5, lower: 0, judgment: '有孚光亨，利涉大川。', image: '云上于天，君子以饮食宴乐。', lines: ['需于郊。','需于沙。','需于泥。','需于血。','需于酒食。','入于穴。'] },
  { id: 6, name: '天水讼', upper: 0, lower: 5, judgment: '中吉终凶，利见大人。', image: '天与水违行，君子以作事谋始。', lines: ['不永所事。','不克讼。','食旧德。','复即命。','讼元吉。','终朝三褫。'] },
  { id: 7, name: '地水师', upper: 7, lower: 5, judgment: '贞丈人吉，无咎。', image: '地中有水，君子以容民畜众。', lines: ['师出以律。','在师中吉。','师或舆尸。','师左次。','田有禽。','开国承家。'] },
  { id: 8, name: '水地比', upper: 5, lower: 7, judgment: '吉，原筮元永贞。', image: '地上有水，先王以建万国。', lines: ['有孚比之。','比之自内。','比之匪人。','外比之。','显比。','比之无首。'] },
  { id: 9, name: '风天小畜', upper: 4, lower: 0, judgment: '亨，密云不雨。', image: '风行天上，君子以懿文德。', lines: ['复自道。','牵复吉。','夫妻反目。','有孚惕出。','富以其邻。','既雨既处。'] },
  { id: 10, name: '天泽履', upper: 0, lower: 1, judgment: '履虎尾不咥人亨。', image: '上天下泽，君子以辨上下。', lines: ['素履。','履道坦坦。','眇能视。','愬愬终吉。','夬履。','视履考祥。'] },
  { id: 11, name: '地天泰', upper: 7, lower: 0, judgment: '小往大来，吉亨。', image: '天地交泰，后以财成天地。', lines: ['拔茅茹。','包荒。','无平不陂。','翩翩不富。','帝乙归妹。','城复于隍。'] },
  { id: 12, name: '天地否', upper: 0, lower: 7, judgment: '不利君子贞。', image: '天地不交，君子以俭德辟难。', lines: ['拔茅茹。','包承。','包羞。','有命无咎。','休否。','倾否。'] },
  { id: 13, name: '天火同人', upper: 0, lower: 2, judgment: '同人于野亨。', image: '天与火，君子以类族辨物。', lines: ['同人于门。','同人于宗。','伏戎于莽。','弗克攻。','先号后笑。','同人于郊。'] },
  { id: 14, name: '火天大有', upper: 2, lower: 0, judgment: '元亨。', image: '火在天上，君子以遏恶扬善。', lines: ['无交害。','大车以载。','公用亨。','匪其彭。','厥孚交如。','自天祐之。'] },
  { id: 15, name: '地山谦', upper: 7, lower: 6, judgment: '亨，君子有终。', image: '地中有山，君子以裒多益寡。', lines: ['谦谦君子。','鸣谦。','劳谦君子。','撝谦。','利用侵伐。','鸣谦征邑。'] },
  { id: 16, name: '雷地豫', upper: 3, lower: 7, judgment: '利建侯行师。', image: '雷出地奋，先王以作乐崇德。', lines: ['鸣豫凶。','介于石。','盱豫悔。','由豫。','贞疾不死。','冥豫。'] },
  { id: 17, name: '泽雷随', upper: 1, lower: 3, judgment: '元亨利贞无咎。', image: '泽中有雷，君子以向晦入宴息。', lines: ['官有渝。','系小子。','系丈夫。','随有获。','孚于嘉。','拘系之。'] },
  { id: 18, name: '山风蛊', upper: 6, lower: 4, judgment: '元亨，利涉大川。', image: '山下有风，君子以振民育德。', lines: ['干父之蛊。','干母之蛊。','小有悔。','裕父之蛊。','用誉。','不事王侯。'] },
  { id: 19, name: '地泽临', upper: 7, lower: 1, judgment: '元亨利贞，至八月凶。', image: '泽上有地，君子以教思无穷。', lines: ['咸临。','咸临吉。','甘临。','至临。','知临。','敦临。'] },
  { id: 20, name: '风地观', upper: 4, lower: 7, judgment: '盥而不荐，有孚颙若。', image: '风行地上，先王以省方观民。', lines: ['童观。','窥观。','观我生。','观国之光。','观我生。','观其生。'] },
  { id: 21, name: '火雷噬嗑', upper: 2, lower: 3, judgment: '亨，利用狱。', image: '雷电噬嗑，先王以明罚敕法。', lines: ['屦校灭趾。','噬肤灭鼻。','噬腊肉。','得金矢。','得黄金。','何校灭耳。'] },
  { id: 22, name: '山火贲', upper: 6, lower: 2, judgment: '亨小，利有攸往。', image: '山下有火，君子以明庶政。', lines: ['贲其趾。','贲其须。','贲如濡如。','贲如皤如。','束帛戋戋。','白贲无咎。'] },
  { id: 23, name: '山地剥', upper: 6, lower: 7, judgment: '不利有攸往。', image: '山附于地，上以厚下安宅。', lines: ['剥床以足。','剥床以辨。','剥之无咎。','剥床以肤。','贯鱼。','硕果不食。'] },
  { id: 24, name: '地雷复', upper: 7, lower: 3, judgment: '出入无疾，朋来无咎。', image: '雷在地中，先王以至日闭关。', lines: ['不远复。','休复吉。','频复。','中行独复。','敦复。','迷复凶。'] },
  { id: 25, name: '天雷无妄', upper: 0, lower: 3, judgment: '元亨利贞，匪正有眚。', image: '天下雷行，物与无妄。', lines: ['无妄往吉。','不耕获。','无妄之灾。','可贞无咎。','无妄之疾。','行有眚。'] },
  { id: 26, name: '山天大畜', upper: 6, lower: 0, judgment: '利贞，利涉大川。', image: '天在山中，君子以多识前言。', lines: ['有厉利已。','舆说輹。','良马逐。','童牛之牿。','豮豕之牙。','何天之衢。'] },
  { id: 27, name: '山雷颐', upper: 6, lower: 3, judgment: '贞吉，自求口实。', image: '山下有雷，君子以慎言语。', lines: ['朵颐。','颠颐。','拂颐。','颠颐吉。','居贞吉。','由颐厉吉。'] },
  { id: 28, name: '泽风大过', upper: 1, lower: 4, judgment: '栋桡，利有攸往亨。', image: '泽灭木，君子以独立不惧。', lines: ['藉用白茅。','枯杨生稊。','栋桡凶。','栋隆吉。','枯杨生华。','过涉灭顶。'] },
  { id: 29, name: '坎为水', upper: 5, lower: 5, judgment: '有孚维心亨，行有尚。', image: '水洊至，君子以常德行。', lines: ['入于坎窞。','坎有险。','来之坎坎。','樽酒簋。','坎不盈。','寘于丛棘。'] },
  { id: 30, name: '离为火', upper: 2, lower: 2, judgment: '利贞亨，畜牝牛吉。', image: '明两作离，大人以继明照四方。', lines: ['履错然。','黄离元吉。','日昃之离。','突如其来。','出涕沱若。','王用出征。'] },
  { id: 31, name: '泽山咸', upper: 1, lower: 6, judgment: '亨，利贞，取女吉。', image: '山上有泽，君子以虚受人。', lines: ['咸其拇。','咸其腓。','咸其股。','贞吉悔亡。','咸其脢。','咸其辅颊。'] },
  { id: 32, name: '雷风恒', upper: 3, lower: 4, judgment: '亨，利贞，利有攸往。', image: '雷风恒，君子以立不易方。', lines: ['浚恒凶。','悔亡。','不恒其德。','田无禽。','恒其德。','振恒凶。'] },
  { id: 33, name: '天山遁', upper: 0, lower: 6, judgment: '亨小，利贞。', image: '天下有山，君子以远小人。', lines: ['遁尾厉。','执之黄牛。','系遁有疾。','好遁。','嘉遁。','肥遁。'] },
  { id: 34, name: '雷天大壮', upper: 3, lower: 0, judgment: '利贞。', image: '雷在天上，君子以非礼弗履。', lines: ['壮于趾。','贞吉。','小人用壮。','贞吉悔亡。','丧羊于易。','羝羊触藩。'] },
  { id: 35, name: '火地晋', upper: 2, lower: 7, judgment: '康侯用锡马蕃庶。', image: '明出地上，君子以自昭明德。', lines: ['晋如摧如。','晋如愁如。','众允。','晋如鼫鼠。','失得勿恤。','晋其角。'] },
  { id: 36, name: '地火明夷', upper: 7, lower: 2, judgment: '利艰贞。', image: '明入地中，君子以莅众。', lines: ['垂其翼。','用拯马壮。','明夷南狩。','入于左腹。','箕子明夷。','初登于天。'] },
  { id: 37, name: '风火家人', upper: 4, lower: 2, judgment: '利女贞。', image: '风自火出，君子以言有物。', lines: ['闲有家。','在中馈。','家人嗃嗃。','富家大吉。','王假有家。','有孚威如。'] },
  { id: 38, name: '火泽睽', upper: 2, lower: 1, judgment: '小事吉。', image: '上火下泽，君子以同而异。', lines: ['丧马勿逐。','遇主于巷。','其牛掣。','遇元夫。','厥宗噬肤。','见豕负涂。'] },
  { id: 39, name: '水山蹇', upper: 5, lower: 6, judgment: '利西南，不利东北。', image: '山上有水，君子以反身修德。', lines: ['往蹇来誉。','王臣蹇蹇。','往蹇来反。','往蹇来连。','大蹇朋来。','往蹇来硕。'] },
  { id: 40, name: '雷水解', upper: 3, lower: 5, judgment: '利西南，其来复吉。', image: '雷雨作，君子以赦过宥罪。', lines: ['无咎。','田获三狐。','致寇至。','朋至斯孚。','维有解吉。','射隼高墉。'] },
  { id: 41, name: '山泽损', upper: 6, lower: 1, judgment: '有孚，元吉，无咎。', image: '山下有泽，君子以惩忿窒欲。', lines: ['遄往无咎。','征凶。','损一人。','使遄有喜。','十朋之龟。','弗损益之。'] },
  { id: 42, name: '风雷益', upper: 4, lower: 3, judgment: '利有攸往，利涉大川。', image: '风雷益，君子以见善则迁。', lines: ['大作。','十朋之龟。','用凶事。','告公从。','有孚惠心。','莫益之。'] },
  { id: 43, name: '泽天夬', upper: 1, lower: 0, judgment: '扬于王庭，孚号有厉。', image: '泽上于天，君子以施禄及下。', lines: ['壮于前趾。','莫夜有戎。','壮于頄。','次且。','苋陆夬夬。','终有凶。'] },
  { id: 44, name: '天风姤', upper: 0, lower: 4, judgment: '女壮，勿用取女。', image: '天下有风，后以施命诰四方。', lines: ['系于金柅。','包有鱼。','行次且。','包无鱼。','含章。','姤其角。'] },
  { id: 45, name: '泽地萃', upper: 1, lower: 7, judgment: '亨，王假有庙。', image: '泽上于地，君子以除戎器。', lines: ['乃乱乃萃。','引吉无咎。','萃如嗟如。','大吉无咎。','萃有位。','賷咨涕洟。'] },
  { id: 46, name: '地风升', upper: 7, lower: 4, judgment: '元亨，用见大人。', image: '地中生木，君子以顺德积小。', lines: ['允升大吉。','利用禴。','升虚邑。','亨于岐山。','升阶。','冥升。'] },
  { id: 47, name: '泽水困', upper: 1, lower: 5, judgment: '亨贞，大人吉。', image: '泽无水，君子以致命遂志。', lines: ['困于株木。','困于酒食。','困于石。','来徐徐。','困于赤绂。','困于葛藟。'] },
  { id: 48, name: '水风井', upper: 5, lower: 4, judgment: '改邑不改井。', image: '木上有水，君子以劳民劝相。', lines: ['井泥不食。','井谷射鲋。','井渫不食。','井甃无咎。','寒泉食。','井收勿幕。'] },
  { id: 49, name: '泽火革', upper: 1, lower: 2, judgment: '己日乃孚，元亨利贞。', image: '泽中有火，君子以治历明时。', lines: ['用黄牛革。','己日革。','三就有孚。','有孚改命。','大人虎变。','君子豹变。'] },
  { id: 50, name: '火风鼎', upper: 2, lower: 4, judgment: '元吉，亨。', image: '木上有火，君子以正位凝命。', lines: ['鼎颠趾。','鼎有实。','鼎耳革。','鼎折足。','鼎黄耳。','鼎玉铉。'] },
  { id: 51, name: '震为雷', upper: 3, lower: 3, judgment: '震来虩虩，笑言哑哑。', image: '洊雷震，君子以恐惧修省。', lines: ['震来虩虩。','震来历。','震苏苏。','震遂泥。','震往来。','震索索。'] },
  { id: 52, name: '艮为山', upper: 6, lower: 6, judgment: '艮其背，不获其身。', image: '兼山艮，君子以思不出位。', lines: ['艮其趾。','艮其腓。','艮其限。','艮其身。','艮其辅。','敦艮吉。'] },
  { id: 53, name: '风山渐', upper: 4, lower: 6, judgment: '女归吉，利贞。', image: '山上有木，君子以居贤德。', lines: ['鸿渐于干。','鸿渐于磐。','鸿渐于陆。','鸿渐于木。','鸿渐于陵。','鸿渐于逵。'] },
  { id: 54, name: '雷泽归妹', upper: 3, lower: 1, judgment: '征凶，无攸利。', image: '泽上有雷，君子以永终知敝。', lines: ['归妹以娣。','眇能视。','归妹以须。','归妹愆期。','帝乙归妹。','女承筐。'] },
  { id: 55, name: '雷火丰', upper: 3, lower: 2, judgment: '亨，王假之。', image: '雷电皆至，君子以折狱致刑。', lines: ['遇配主。','丰其蔀。','丰其沛。','遇夷主。','有庆誉。','丰其屋。'] },
  { id: 56, name: '火山旅', upper: 2, lower: 6, judgment: '小亨，旅贞吉。', image: '山上有火，君子以明慎用刑。', lines: ['旅琐琐。','旅即次。','旅焚次。','旅于处。','射雉亡。','鸟焚巢。'] },
  { id: 57, name: '巽为风', upper: 4, lower: 4, judgment: '小亨，利有攸往。', image: '随风巽，君子以申命行事。', lines: ['利武人贞。','巽在床下。','频巽吝。','田获三品。','贞吉悔亡。','丧资斧。'] },
  { id: 58, name: '兑为泽', upper: 1, lower: 1, judgment: '亨，利贞。', image: '丽泽兑，君子以朋友讲习。', lines: ['和兑吉。','孚兑吉。','来兑凶。','商兑未宁。','孚于剥。','引兑。'] },
  { id: 59, name: '风水涣', upper: 4, lower: 5, judgment: '亨，王假有庙。', image: '风行水上，先王以享于帝。', lines: ['用拯马壮。','涣奔其机。','涣其躬。','涣其群。','涣其大号。','涣其血。'] },
  { id: 60, name: '水泽节', upper: 5, lower: 1, judgment: '亨，苦节不可贞。', image: '泽上有水，君子以制数度。', lines: ['不出户庭。','不出门庭。','不节若。','安节亨。','甘节吉。','苦节凶。'] },
  { id: 61, name: '风泽中孚', upper: 4, lower: 1, judgment: '中孚豚鱼吉。', image: '泽上有风，君子以议狱缓死。', lines: ['虞吉。','鸣鹤在阴。','得敌。','月几望。','有孚挛如。','翰音登天。'] },
  { id: 62, name: '雷山小过', upper: 3, lower: 6, judgment: '亨，小事不可大事。', image: '山上有雷，君子以行过乎恭。', lines: ['飞鸟以凶。','遇其妣。','弗过防之。','弗过遇之。','密云不雨。','飞鸟离之。'] },
  { id: 63, name: '水火既济', upper: 5, lower: 2, judgment: '亨小，利贞，初吉终乱。', image: '水在火上，君子以思患豫防。', lines: ['濡其尾。','妇丧茀。','伐鬼方。','繻有衣袽。','东邻杀牛。','濡其首。'] },
  { id: 64, name: '火水未济', upper: 2, lower: 5, judgment: '亨，小狐汔济。', image: '火在水上，君子以慎辨物居方。', lines: ['濡其尾。','曳其轮。','未济征凶。','震用伐。','君子之光。','饮酒濡首。'] },
]
